# Generated by Django 6.0.3 on 2026-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_code", models.CharField(max_length=20, unique=True)),
                ("dept_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(blank=True, max_length=50)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("정규직", "정규직"),
                            ("계약직", "계약직"),
                            ("파견직", "파견직"),
                            ("인턴", "인턴"),
                        ],
                        default="정규직",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField()),
                ("resign_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("재직", "재직"), ("퇴직", "퇴직"), ("휴직", "휴직")],
                        default="재직",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "base_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_hr.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payroll_number", models.CharField(max_length=50, unique=True)),
                ("pay_year", models.IntegerField()),
                ("pay_month", models.IntegerField()),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "overtime_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("gross_pay", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "national_pension",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "health_insurance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "employment_insurance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "income_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "state",
                    models.CharField(
                        choices=[("DRAFT", "임시"), ("확정", "확정")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_hr.employee",
                    ),
                ),
            ],
        ),
    ]
