# Generated by Django 6.0.3 on 2026-03-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_tm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transport_number", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(max_length=200)),
                ("status_note", models.CharField(blank=True, max_length=200)),
                ("tracked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "transport_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to="scm_tm.transportorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-tracked_at", "-created_at"],
            },
        ),
    ]
