# Generated by Django 6.0.3 on 2026-03-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("approval_request", "결재요청"),
                            ("approval_result", "결재결과"),
                            ("deadline_warning", "납기임박"),
                            ("low_stock", "부족재고"),
                            ("inspection_result", "검사결과"),
                            ("system", "시스템"),
                        ],
                        max_length=30,
                        verbose_name="알림유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("message", models.TextField(verbose_name="내용")),
                ("is_read", models.BooleanField(default=False, verbose_name="읽음")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="읽은 일시"
                    ),
                ),
                (
                    "ref_module",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="참조 모듈"
                    ),
                ),
                (
                    "ref_id",
                    models.IntegerField(blank=True, null=True, verbose_name="참조 ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="scm_notific_recipie_90b429_idx",
                    ),
                    models.Index(
                        fields=["company", "notification_type"],
                        name="scm_notific_company_7f638d_idx",
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="scm_notific_recipie_ad40d4_idx",
                    ),
                ],
            },
        ),
    ]
