# Generated by Django 6.0.3 on 2026-03-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("scm_accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_no", models.IntegerField(verbose_name="단계번호")),
                ("step_name", models.CharField(max_length=100, verbose_name="단계명")),
                (
                    "approver_role",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="결재자 역할"
                    ),
                ),
            ],
            options={
                "verbose_name": "결재 단계",
                "verbose_name_plural": "결재 단계",
                "ordering": ["template", "step_no"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "current_step",
                    models.IntegerField(default=1, verbose_name="현재 단계"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("approved", "승인"),
                            ("rejected", "반려"),
                            ("cancelled", "취소"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="결재 제목"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청일시"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료일시"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "결재 요청",
                "verbose_name_plural": "결재 요청",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "승인"),
                            ("rejected", "반려"),
                            ("delegated", "위임"),
                        ],
                        max_length=20,
                        verbose_name="행동",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="의견")),
                (
                    "acted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="처리일시"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="scm_workflow.approvalrequest",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="scm_workflow.approvalstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "결재 행위",
                "verbose_name_plural": "결재 행위",
                "ordering": ["request", "acted_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="템플릿명")),
                ("module", models.CharField(max_length=50, verbose_name="모듈")),
                ("doc_type", models.CharField(max_length=50, verbose_name="문서유형")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_templates",
                        to="scm_accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "결재 템플릿",
                "verbose_name_plural": "결재 템플릿",
                "ordering": ["company", "module", "doc_type"],
                "unique_together": {("company", "module", "doc_type")},
            },
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="scm_workflow.approvaltemplate",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="scm_workflow.approvaltemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="approvalstep",
            unique_together={("template", "step_no")},
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["company", "status"], name="scm_workflo_company_c834b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["requester", "status"], name="scm_workflo_request_bb4f18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="scm_workflo_content_ed7a02_idx",
            ),
        ),
    ]
