# Generated by Django 6.0.3 on 2026-03-27 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_mm", "0002_goodsreceipt_add_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boms",
                        to="scm_mm.material",
                        verbose_name="완제품/반제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM",
                "verbose_name_plural": "BOM 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BOMLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("unit", models.CharField(default="EA", max_length=20)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="scm_pp.bom",
                    ),
                ),
                (
                    "component_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_lines",
                        to="scm_mm.material",
                        verbose_name="구성 자재",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM 라인",
                "verbose_name_plural": "BOM 라인 목록",
            },
        ),
        migrations.CreateModel(
            name="MRPPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_date", models.DateField(verbose_name="계획 기준일")),
                (
                    "required_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="소요 수량"
                    ),
                ),
                (
                    "available_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="가용 수량",
                    ),
                ),
                (
                    "shortage_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="부족 수량",
                    ),
                ),
                (
                    "suggested_order_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="발주 제안 수량",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "검토중"),
                            ("ORDERED", "발주완료"),
                            ("CLOSED", "완료"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mrp_plans",
                        to="scm_mm.material",
                        verbose_name="자재",
                    ),
                ),
            ],
            options={
                "verbose_name": "MRP 계획",
                "verbose_name_plural": "MRP 계획 목록",
                "ordering": ["-plan_date", "material"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="생산오더번호"
                    ),
                ),
                (
                    "planned_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="계획 수량"
                    ),
                ),
                (
                    "actual_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="실적 수량",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "초안"),
                            ("RELEASED", "릴리즈"),
                            ("IN_PROGRESS", "진행중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "planned_start",
                    models.DateField(blank=True, null=True, verbose_name="계획 시작일"),
                ),
                (
                    "planned_end",
                    models.DateField(blank=True, null=True, verbose_name="계획 종료일"),
                ),
                (
                    "actual_start",
                    models.DateField(blank=True, null=True, verbose_name="실제 시작일"),
                ),
                (
                    "actual_end",
                    models.DateField(blank=True, null=True, verbose_name="실제 종료일"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders",
                        to="scm_pp.bom",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "생산오더",
                "verbose_name_plural": "생산오더 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
