# Generated by Django 6.0.3 on 2026-03-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "생성"),
                            ("UPDATE", "수정"),
                            ("DELETE", "삭제"),
                        ],
                        max_length=10,
                        verbose_name="작업",
                    ),
                ),
                ("module", models.CharField(max_length=50, verbose_name="모듈")),
                ("model_name", models.CharField(max_length=100, verbose_name="모델명")),
                ("object_id", models.IntegerField(verbose_name="객체 ID")),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="객체 표현"
                    ),
                ),
                ("changes", models.JSONField(default=dict, verbose_name="변경 내역")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User-Agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기록일시"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "감사 로그",
                "verbose_name_plural": "감사 로그",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "module"],
                        name="scm_core_au_company_d5fe25_idx",
                    ),
                    models.Index(
                        fields=["company", "model_name", "object_id"],
                        name="scm_core_au_company_936b6e_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="scm_core_au_user_id_0ab16f_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="scm_core_au_action_456242_idx",
                    ),
                ],
            },
        ),
    ]
