# Generated by Django 6.0.3 on 2026-03-27 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="운송사 코드"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="운송사명")),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="담당자명"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="전화번호"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "운송사",
                "verbose_name_plural": "운송사 목록",
            },
        ),
        migrations.CreateModel(
            name="TransportOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="운송지시번호"
                    ),
                ),
                (
                    "origin_address",
                    models.CharField(max_length=500, verbose_name="출발지 주소"),
                ),
                (
                    "destination_address",
                    models.CharField(max_length=500, verbose_name="도착지 주소"),
                ),
                (
                    "cargo_description",
                    models.TextField(blank=True, verbose_name="화물 내용"),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="중량(kg)",
                    ),
                ),
                (
                    "volume_cbm",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="부피(CBM)",
                    ),
                ),
                (
                    "planned_departure",
                    models.DateTimeField(verbose_name="예정 출발일시"),
                ),
                (
                    "actual_departure",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="실제 출발일시"
                    ),
                ),
                ("planned_arrival", models.DateTimeField(verbose_name="예정 도착일시")),
                (
                    "actual_arrival",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="실제 도착일시"
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="운임(원)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "임시"),
                            ("CONFIRMED", "확정"),
                            ("IN_TRANSIT", "운송중"),
                            ("DELIVERED", "배송완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("PO", "구매오더"),
                            ("SO", "판매오더"),
                            ("OTHER", "기타"),
                        ],
                        default="OTHER",
                        max_length=10,
                        verbose_name="참조 유형",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="참조번호"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_orders",
                        to="scm_tm.carrier",
                        verbose_name="운송사",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                        verbose_name="회사",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_orders_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "운송지시",
                "verbose_name_plural": "운송지시 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=300, verbose_name="현재 위치"),
                ),
                ("status_update", models.TextField(verbose_name="상태 업데이트 내용")),
                ("timestamp", models.DateTimeField(verbose_name="기록 일시")),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="기록자",
                    ),
                ),
                (
                    "transport_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_records",
                        to="scm_tm.transportorder",
                        verbose_name="운송지시",
                    ),
                ),
            ],
            options={
                "verbose_name": "운송 추적",
                "verbose_name_plural": "운송 추적 이력",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["company", "is_active"], name="scm_tm_carr_company_f4ade1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["carrier_code"], name="scm_tm_carr_carrier_6675e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportorder",
            index=models.Index(
                fields=["company", "status"], name="scm_tm_tran_company_871486_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportorder",
            index=models.Index(
                fields=["company", "planned_departure"],
                name="scm_tm_tran_company_e1394d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transportorder",
            index=models.Index(
                fields=["carrier"], name="scm_tm_tran_carrier_9d46b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportorder",
            index=models.Index(
                fields=["order_number"], name="scm_tm_tran_order_n_6708bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transporttracking",
            index=models.Index(
                fields=["transport_order", "timestamp"],
                name="scm_tm_tran_transpo_f9c326_idx",
            ),
        ),
    ]
