# Generated by Django 6.0.3 on 2026-04-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0002_role_userrole"),
        ("scm_wi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard_code",
                    models.CharField(
                        help_text="작업표준 코드 (여러 버전 공유)", max_length=50
                    ),
                ),
                ("work_center", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True, help_text="작업 절차 상세")),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("active", "활성"),
                            ("deprecated", "폐기"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["standard_code", "-version"],
                "unique_together": {("company", "standard_code", "version")},
            },
        ),
    ]
