# Generated by Django 6.0.3 on 2026-03-27 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_mm", "0002_goodsreceipt_add_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("INCOMING", "수입검사"),
                            ("PROCESS", "공정검사"),
                            ("FINAL", "최종검사"),
                            ("PERIODIC", "정기검사"),
                        ],
                        default="INCOMING",
                        max_length=20,
                        verbose_name="검사 유형",
                    ),
                ),
                (
                    "sampling_method",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="샘플링 방법"
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(default=1, verbose_name="샘플 크기"),
                ),
                ("criteria", models.TextField(blank=True, verbose_name="합격 기준")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_plans",
                        to="scm_mm.material",
                        verbose_name="대상 자재",
                    ),
                ),
            ],
            options={
                "verbose_name": "검사계획",
                "verbose_name_plural": "검사계획 목록",
                "ordering": ["inspection_type", "material"],
            },
        ),
        migrations.CreateModel(
            name="InspectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[("GR", "입고"), ("SO", "출고"), ("PERIODIC", "정기")],
                        default="GR",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="참조번호"
                    ),
                ),
                (
                    "inspected_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="검사 수량",
                    ),
                ),
                (
                    "passed_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="합격 수량",
                    ),
                ),
                (
                    "failed_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="불합격 수량",
                    ),
                ),
                ("inspection_date", models.DateField(verbose_name="검사일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "검사중"),
                            ("PASSED", "합격"),
                            ("FAILED", "불합격"),
                            ("CONDITIONAL", "조건부합격"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="비고")),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="검사자",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="scm_qm.inspectionplan",
                        verbose_name="검사계획",
                    ),
                ),
            ],
            options={
                "verbose_name": "검사결과",
                "verbose_name_plural": "검사결과 목록",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="DefectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(max_length=100, verbose_name="결함 유형"),
                ),
                (
                    "defect_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=15,
                        verbose_name="결함 수량",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "경결함"),
                            ("MAJOR", "중결함"),
                            ("CRITICAL", "치명결함"),
                        ],
                        default="MINOR",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="결함 설명")),
                (
                    "corrective_action",
                    models.TextField(blank=True, verbose_name="시정 조치"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "미처리"),
                            ("IN_PROGRESS", "처리중"),
                            ("CLOSED", "완료"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defect_reports",
                        to="scm_qm.inspectionresult",
                        verbose_name="검사결과",
                    ),
                ),
            ],
            options={
                "verbose_name": "결함보고",
                "verbose_name_plural": "결함보고 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
