# Generated by Django 6.0.3 on 2026-03-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_mm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfq_number", models.CharField(max_length=50, unique=True)),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("required_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("sent", "발송"),
                            ("received", "견적수신"),
                            ("closed", "마감"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_mm.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eval_year", models.IntegerField()),
                ("eval_month", models.IntegerField()),
                (
                    "delivery_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "quality_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "price_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("grade", models.CharField(blank=True, max_length=5)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_mm.supplier",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "supplier", "eval_year", "eval_month")},
            },
        ),
    ]
