# Generated by Django 6.0.3 on 2026-03-29 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_mm", "0002_rfq_supplierevaluation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("purchase", "구매단가"), ("standard", "표준원가")],
                        default="purchase",
                        max_length=20,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="KRW", max_length=10)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="scm_mm.material",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_mm.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
    ]
