# Generated by Django 6.0.3 on 2026-03-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_mm", "0003_material_price_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField(default=1)),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("unit", models.CharField(default="EA", max_length=20)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_mm.material",
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="scm_mm.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["line_no"],
            },
        ),
    ]
