# Generated by Django 6.0.3 on 2026-04-11 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0003_userpermission_can_delete"),
        ("scm_mm", "0004_purchase_order_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="lead_time_days",
            field=models.IntegerField(default=7),
        ),
        migrations.CreateModel(
            name="SupplierMaterialConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_time_days", models.IntegerField(default=7)),
                ("min_order_qty", models.IntegerField(default=1)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_configs",
                        to="scm_mm.material",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_configs",
                        to="scm_mm.supplier",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "material", "supplier")},
            },
        ),
    ]
