# Generated by Django 6.0.3 on 2026-03-22 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warehouse_code", models.CharField(max_length=20, unique=True)),
                ("warehouse_name", models.CharField(max_length=100)),
                ("warehouse_type", models.CharField(default="일반창고", max_length=50)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=100)),
                ("item_name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("bin_code", models.CharField(blank=True, max_length=50)),
                ("stock_qty", models.IntegerField(default=0)),
                ("system_qty", models.IntegerField(default=0)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("min_stock", models.IntegerField(default=0)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("lot_number", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_wm.warehouse",
                    ),
                ),
            ],
            options={
                "unique_together": {("item_code", "warehouse", "lot_number")},
            },
        ),
    ]
