# Generated by Django 6.0.3 on 2026-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "자산"),
                            ("LIABILITY", "부채"),
                            ("EQUITY", "자본"),
                            ("REVENUE", "수익"),
                            ("EXPENSE", "비용"),
                        ],
                        max_length=20,
                    ),
                ),
                ("root_type", models.CharField(blank=True, max_length=50)),
                ("is_group", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="AccountMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_number", models.CharField(max_length=50, unique=True)),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("ENTRY", "일반"),
                            ("PURCHASE", "매입"),
                            ("SALE", "매출"),
                            ("PAYMENT", "지급"),
                            ("RECEIPT", "수금"),
                            ("ADJUST", "조정"),
                        ],
                        max_length=20,
                    ),
                ),
                ("posting_date", models.DateField()),
                ("ref", models.CharField(blank=True, max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "임시"),
                            ("POSTED", "확정"),
                            ("CANCELLED", "취소"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountMoveLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("is_reconciled", models.BooleanField(default=False)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="scm_fi.account"
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="scm_fi.accountmove",
                    ),
                ),
            ],
        ),
    ]
