# Generated by Django 6.0.3 on 2026-03-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_fi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_code", models.CharField(max_length=50)),
                ("asset_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("machinery", "기계"),
                            ("vehicle", "차량"),
                            ("equipment", "설비"),
                            ("furniture", "비품"),
                            ("intangible", "무형자산"),
                        ],
                        max_length=50,
                    ),
                ),
                ("acquisition_date", models.DateField()),
                (
                    "acquisition_cost",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("useful_life_years", models.IntegerField(default=5)),
                (
                    "salvage_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[("straight_line", "정액법"), ("declining", "정률법")],
                        default="straight_line",
                        max_length=20,
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "book_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "사용중"),
                            ("disposed", "처분"),
                            ("retired", "폐기"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "asset_code")},
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_year", models.IntegerField()),
                ("budget_month", models.IntegerField(blank=True, null=True)),
                (
                    "budgeted_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "actual_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scm_fi.account"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("company", "budget_year", "budget_month", "account")
                },
            },
        ),
        migrations.CreateModel(
            name="DepreciationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_year", models.IntegerField()),
                ("period_month", models.IntegerField()),
                (
                    "depreciation_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "accumulated_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "book_value_after",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("is_posted", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="scm_fi.fixedasset",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "period_year", "period_month")},
            },
        ),
    ]
