# Generated by Django 6.0.3 on 2026-03-28 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_fi", "0002_fixedasset_budget_depreciationschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("SALE", "매출"), ("PURCHASE", "매입")],
                        default="SALE",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "counterpart",
                    models.CharField(max_length=200, verbose_name="거래처"),
                ),
                (
                    "supply_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="공급가액",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="부가세",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="합계금액",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "임시"),
                            ("issued", "발행"),
                            ("cancelled", "취소"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("remark", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
        ),
    ]
