# Generated by Django 6.0.3 on 2026-03-27 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_fi", "0002_add_period_and_lock_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="세금계산서 번호"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("PURCHASE", "매입"), ("SALE", "매출")],
                        max_length=10,
                        verbose_name="유형(매입/매출)",
                    ),
                ),
                (
                    "supplier_or_customer_name",
                    models.CharField(max_length=200, verbose_name="공급자/수요자명"),
                ),
                (
                    "supply_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="공급가액"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="세액"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="합계금액"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="발행일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "임시"),
                            ("ISSUED", "발행"),
                            ("CANCELLED", "취소"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "세금계산서",
                "verbose_name_plural": "세금계산서 목록",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="accountmove",
            new_name="scm_fi_acco_company_fcacfb_idx",
            old_name="scm_fi_acc_company_period_idx",
        ),
        migrations.RenameIndex(
            model_name="accountmove",
            new_name="scm_fi_acco_company_fd90a1_idx",
            old_name="scm_fi_acc_company_state_idx",
        ),
        migrations.RenameIndex(
            model_name="accountmove",
            new_name="scm_fi_acco_posting_62f4ca_idx",
            old_name="scm_fi_acc_posting_date_idx",
        ),
        migrations.RenameIndex(
            model_name="accountmoveline",
            new_name="scm_fi_acco_account_566c83_idx",
            old_name="scm_fi_line_account_idx",
        ),
        migrations.RenameIndex(
            model_name="accountmoveline",
            new_name="scm_fi_acco_move_id_223bea_idx",
            old_name="scm_fi_line_move_idx",
        ),
        migrations.AddField(
            model_name="taxinvoice",
            name="account_move",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tax_invoices",
                to="scm_fi.accountmove",
                verbose_name="연결 전표",
            ),
        ),
        migrations.AddField(
            model_name="taxinvoice",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scm_accounts.company",
                verbose_name="회사",
            ),
        ),
        migrations.AddField(
            model_name="taxinvoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tax_invoices_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddIndex(
            model_name="taxinvoice",
            index=models.Index(
                fields=["company", "invoice_type", "status"],
                name="scm_fi_taxi_company_8de2cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxinvoice",
            index=models.Index(
                fields=["company", "issue_date"], name="scm_fi_taxi_company_093bca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxinvoice",
            index=models.Index(
                fields=["invoice_number"], name="scm_fi_taxi_invoice_6377d6_idx"
            ),
        ),
    ]
