# Generated by Django 6.0.3 on 2026-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillOfMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bom_code", models.CharField(max_length=50, unique=True)),
                ("product_name", models.CharField(max_length=200)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BomLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_code", models.CharField(max_length=50)),
                ("material_name", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(default="EA", max_length=20)),
                (
                    "scrap_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="scm_pp.billofmaterial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MrpRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_number", models.CharField(max_length=50, unique=True)),
                ("run_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("실행중", "실행중"),
                            ("완료", "완료"),
                            ("오류", "오류"),
                        ],
                        default="실행중",
                        max_length=20,
                    ),
                ),
                ("total_items", models.IntegerField(default=0)),
                ("planned_orders", models.IntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("product_name", models.CharField(max_length=200)),
                ("planned_qty", models.IntegerField()),
                ("produced_qty", models.IntegerField(default=0)),
                ("defect_qty", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("계획", "계획"),
                            ("확정", "확정"),
                            ("생산중", "생산중"),
                            ("완료", "완료"),
                            ("취소", "취소"),
                        ],
                        default="계획",
                        max_length=20,
                    ),
                ),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_end", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_end", models.DateField(blank=True, null=True)),
                ("work_center", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_pp.billofmaterial",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
        ),
    ]
