# Generated by Django 6.0.3 on 2026-04-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0002_role_userrole"),
        ("scm_pp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="actual_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="실제 작업시간 (시간)",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="labor_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="인건비 합계", max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="material_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="자재원가 합계 (자동계산)",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="planned_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="계획 작업시간 (시간)",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="process_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="공정비 (기계비+간접비) 합계",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="총원가 = 자재+공정+인건비",
                max_digits=15,
            ),
        ),
        migrations.CreateModel(
            name="WorkCenterCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_center", models.CharField(max_length=100)),
                (
                    "machine_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="시간당 기계/공정비 (원)",
                        max_digits=12,
                    ),
                ),
                (
                    "labor_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="시간당 인건비 표준단가 (원)",
                        max_digits=12,
                    ),
                ),
                (
                    "overhead_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="시간당 간접비 (원)",
                        max_digits=12,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
    ]
