# Generated by Django 6.0.3 on 2026-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_code", models.CharField(max_length=20, unique=True)),
                ("customer_name", models.CharField(max_length=200)),
                ("contact", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("payment_terms", models.CharField(default="30일", max_length=50)),
                ("status", models.CharField(default="활성", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("customer_name", models.CharField(max_length=200)),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "discount_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("주문접수", "주문접수"),
                            ("생산/조달중", "생산/조달중"),
                            ("출하준비", "출하준비"),
                            ("배송중", "배송중"),
                            ("배송완료", "배송완료"),
                            ("취소", "취소"),
                        ],
                        default="주문접수",
                        max_length=20,
                    ),
                ),
                ("shipped_qty", models.IntegerField(default=0)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_sd.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_number", models.CharField(max_length=50, unique=True)),
                ("item_name", models.CharField(max_length=200)),
                ("delivery_qty", models.IntegerField()),
                ("carrier", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="출하준비", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_sd.salesorder",
                    ),
                ),
            ],
        ),
    ]
