# Generated by Django 6.0.3 on 2026-03-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_sd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerCreditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_sd.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.IntegerField(default=1)),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "discount_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="scm_sd.salesorder",
                    ),
                ),
            ],
        ),
    ]
