# Generated by Django 6.0.3 on 2026-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("defect_number", models.CharField(max_length=50, unique=True)),
                ("item_name", models.CharField(max_length=200)),
                ("defect_type", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("경미", "경미"),
                            ("보통", "보통"),
                            ("심각", "심각"),
                            ("치명", "치명"),
                        ],
                        default="보통",
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorrectiveAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capa_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("root_cause", models.TextField(blank=True)),
                ("action_plan", models.TextField(blank=True)),
                ("responsible", models.CharField(blank=True, max_length=100)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("등록", "등록"),
                            ("조사중", "조사중"),
                            ("이행중", "이행중"),
                            ("완료", "완료"),
                            ("종결", "종결"),
                        ],
                        default="등록",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "defect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="scm_qm.defectrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_code", models.CharField(max_length=50, unique=True)),
                ("plan_name", models.CharField(max_length=200)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("수입검사", "수입검사"),
                            ("공정검사", "공정검사"),
                            ("출하검사", "출하검사"),
                            ("정기검사", "정기검사"),
                        ],
                        default="수입검사",
                        max_length=20,
                    ),
                ),
                ("target_item", models.CharField(blank=True, max_length=200)),
                ("criteria", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_number", models.CharField(max_length=50, unique=True)),
                ("item_name", models.CharField(max_length=200)),
                ("lot_number", models.CharField(blank=True, max_length=100)),
                ("inspected_qty", models.IntegerField(default=0)),
                ("passed_qty", models.IntegerField(default=0)),
                ("failed_qty", models.IntegerField(default=0)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("합격", "합격"),
                            ("불합격", "불합격"),
                            ("조건부합격", "조건부합격"),
                        ],
                        default="합격",
                        max_length=20,
                    ),
                ),
                ("inspector", models.CharField(blank=True, max_length=100)),
                ("inspected_at", models.DateTimeField(blank=True, null=True)),
                ("remark", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_qm.inspectionplan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="defectrecord",
            name="inspection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="defects",
                to="scm_qm.inspectionresult",
            ),
        ),
    ]
