# Generated by Django 6.0.3 on 2026-03-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_qm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ncr_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("responsible", models.CharField(blank=True, max_length=100)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "개설"),
                            ("in_progress", "처리중"),
                            ("closed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "defect_ref_number",
                    models.CharField(max_length=50, blank=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SPCData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement_name", models.CharField(max_length=100)),
                (
                    "measured_value",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "usl",
                    models.DecimalField(decimal_places=4, max_digits=15, null=True),
                ),
                (
                    "lsl",
                    models.DecimalField(decimal_places=4, max_digits=15, null=True),
                ),
                (
                    "target",
                    models.DecimalField(decimal_places=4, max_digits=15, null=True),
                ),
                ("measured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "inspection_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spc_data",
                        to="scm_qm.inspectionresult",
                    ),
                ),
            ],
        ),
    ]
