# Generated by Django 6.0.3 on 2026-04-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scm_accounts", "0003_userpermission_can_delete"),
        ("scm_mm", "0005_supplier_lead_time_days_suppliermaterialconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubcontractOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("order_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("work_description", models.CharField(blank=True, max_length=500)),
                ("currency", models.CharField(default="KRW", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("issued", "발주확정"),
                            ("in_progress", "작업중"),
                            ("completed", "작업완료"),
                            ("received", "입고완료"),
                            ("closed", "마감"),
                            ("cancelled", "취소"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_sub_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_mm.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubcontractMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(default="EA", max_length=20)),
                (
                    "issued_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "returned_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_mm.material",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="scm_sub.subcontractorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubcontractOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField(default=1)),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(default="EA", max_length=20)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="scm_sub.subcontractorder",
                    ),
                ),
            ],
            options={
                "ordering": ["line_no"],
            },
        ),
        migrations.CreateModel(
            name="SubcontractReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("receipt_date", models.DateField()),
                ("item_name", models.CharField(max_length=200)),
                (
                    "ordered_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("received_qty", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "rejected_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("warehouse", models.CharField(blank=True, max_length=100)),
                ("receiver", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="scm_sub.subcontractorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
