# Generated by Django 6.0.3 on 2026-03-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_wm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CycleCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_number", models.CharField(max_length=50, unique=True)),
                ("count_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "계획"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("counter", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_wm.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CycleCountLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_qty", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "counted_qty",
                    models.DecimalField(decimal_places=3, max_digits=15, null=True),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=3, max_digits=15, null=True),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "cycle_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="scm_wm.cyclecount",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_wm.inventory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BinLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bin_code", models.CharField(max_length=50)),
                ("aisle", models.CharField(blank=True, max_length=20)),
                ("row", models.CharField(blank=True, max_length=20)),
                ("level", models.CharField(blank=True, max_length=20)),
                (
                    "capacity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_wm.warehouse",
                    ),
                ),
            ],
            options={
                "unique_together": {("warehouse", "bin_code")},
            },
        ),
    ]
