# Generated by Django 6.0.3 on 2026-03-28 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm_accounts", "0001_initial"),
        ("scm_wm", "0002_cyclecount_cyclecountline_binlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "입고"),
                            ("OUT", "출고"),
                            ("TRANSFER", "이동"),
                            ("ADJUST", "조정"),
                        ],
                        max_length=20,
                    ),
                ),
                ("material_code", models.CharField(max_length=100)),
                ("material_name", models.CharField(blank=True, max_length=200)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_document", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scm_accounts.company",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scm_wm.warehouse",
                    ),
                ),
            ],
        ),
    ]
