/**
 * SCM2 type barrel — re-exports every type from api.ts so consumers can
 * import from a single entry-point:
 *
 *   import type { Supplier, CreateSupplier, PaginatedResponse } from '@/types'
 */

export type {
  // Utility
  PaginatedResponse,
  ApiError,

  // scm_accounts
  CompanyPlan,
  Company,
  CreateCompany,
  UpdateCompany,
  User,
  UserPermission,

  // MM — Material Management
  PurchaseOrderStatus,
  Supplier,
  CreateSupplier,
  UpdateSupplier,
  Material,
  CreateMaterial,
  UpdateMaterial,
  PurchaseOrder,
  CreatePurchaseOrder,
  UpdatePurchaseOrder,
  GoodsReceipt,
  CreateGoodsReceipt,
  UpdateGoodsReceipt,
  RfqStatus,
  RFQ,
  CreateRFQ,
  UpdateRFQ,
  SupplierEvaluation,
  CreateSupplierEvaluation,
  UpdateSupplierEvaluation,

  // SD — Sales & Distribution
  SalesOrderStatus,
  Customer,
  CreateCustomer,
  UpdateCustomer,
  SalesOrderLine,
  CreateSalesOrderLine,
  UpdateSalesOrderLine,
  SalesOrder,
  CreateSalesOrder,
  UpdateSalesOrder,
  Delivery,
  CreateDelivery,
  UpdateDelivery,
  CustomerCreditHistory,

  // WM — Warehouse Management
  StockMovementType,
  StockMovementReferenceType,
  Warehouse,
  CreateWarehouse,
  UpdateWarehouse,
  Inventory,
  CreateInventory,
  UpdateInventory,
  StockMovement,
  BinLocation,
  CreateBinLocation,
  UpdateBinLocation,
  CycleCountStatus,
  CycleCount,
  CycleCountLine,

  // PP — Production Planning
  ProductionOrderStatus,
  MrpRunStatus,
  BillOfMaterial,
  CreateBillOfMaterial,
  UpdateBillOfMaterial,
  BomLine,
  CreateBomLine,
  UpdateBomLine,
  ProductionOrder,
  CreateProductionOrder,
  UpdateProductionOrder,
  MrpRun,
  CreateMrpRun,
  UpdateMrpRun,

  // HR — Human Resources
  EmployeeStatus,
  EmploymentType,
  AttendanceWorkType,
  LeaveType,
  LeaveStatus,
  PayrollState,
  Department,
  CreateDepartment,
  UpdateDepartment,
  Employee,
  CreateEmployee,
  UpdateEmployee,
  Payroll,
  CreatePayroll,
  UpdatePayroll,
  Attendance,
  CreateAttendance,
  UpdateAttendance,
  Leave,
  CreateLeave,
  UpdateLeave,
  LeaveBalance,

  // FI — Finance
  AccountType,
  AccountMoveState,
  AccountMoveType,
  FixedAssetCategory,
  FixedAssetDepreciationMethod,
  FixedAssetStatus,
  TaxInvoiceType,
  TaxInvoiceStatus,
  Account,
  CreateAccount,
  UpdateAccount,
  AccountMoveLine,
  CreateAccountMoveLine,
  UpdateAccountMoveLine,
  AccountMove,
  CreateAccountMove,
  UpdateAccountMove,
  Budget,
  CreateBudget,
  UpdateBudget,
  FixedAsset,
  CreateFixedAsset,
  UpdateFixedAsset,
  DepreciationSchedule,
  TaxInvoice,
  CreateTaxInvoice,
  UpdateTaxInvoice,

  // QM — Quality Management
  InspectionType,
  InspectionResultValue,
  DefectSeverity,
  CorrectiveActionStatus,
  InspectionPlan,
  CreateInspectionPlan,
  UpdateInspectionPlan,
  InspectionResult,
  CreateInspectionResult,
  UpdateInspectionResult,
  DefectRecord,
  CreateDefectRecord,
  UpdateDefectRecord,
  CorrectiveAction,
  CreateCorrectiveAction,
  UpdateCorrectiveAction,
  SPCData,
  NcrStatus,
  NCR,
  CreateNCR,
  UpdateNCR,
} from "./api";
